# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 012b9afa2218895a76ebcf1030eea8d47b311361a982b19dd9505502b4fa4e051a0b02e6f3e82adc31737f3374ffb7e179d33037855e780aee8ef1ea9837b688

test:
  secret_key_base: e2c686b3bf26315531c69a9fd7e0d28b76a0842877b3b6341cc661da8c1bc8052b86dd8daff654693b50a46ce190a996f93cca7566441501c25fb7915739d536

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
